language: node_js
node_js:
- '10'
- '9'
- '8'
deploy:
  provider: npm
  email: apps@ludei.com
  api_key:
    secure: ucszWEMOcrVgo8jhPvtMMbDcD08fg/x+gKW5ZCt1pMTFScqAnmD+qmacaolXrPWlwo07ZY9Dlzvv3e+OQruqRHuYuCa4P/UTIPMxOpUUcskb+Z3iut0lbd4FgijngWM/N0x7ehBny5Ceq83lxSZGe2eu9aIE9HFIpphI3Uz+lNOzXDTnjxXA8T1kI5zdYj1SJWB/ils0rcwnyg8EVQC5aWlWhyvVtUkrpbp+zZLrJo37pOCSeWck1eYTqo4aTPO579Ky2OauC48WGcR6ffUazt7XTvFB/h5QTW62ds4S0AOp7MuUHBBbaeQbr04Y0RppK3tD1/32dxH8KrUb8aF/HHpgFhctNG04UgoOIDyAlB5NbMskbCiebQ1Fx73im9enalp0O1uuy/DxOrUS51NZquolcZD/nIK/DRWAJAi3ckr7EJS8nlGrlK/Yqw9tRNQWs68BeBPm0YDnyOHABcBhw512i3CH9I5FzZ0t8qIX40LlRpPajp9vQ4e0sN4gzU1PSlc0yLQaQOlcxT7cgjkzVi2UlKdZUhBZHCx9NDImDAikBjOyc925tklvVDPmuZAWPBdTR9Xp0pXLj0ibZFTiRqgQ8GOa+yVTFwkzO6yHwZPOyL8IKDIQqN6RAHyRnWQZAXSPDGR4pzy9nf0EOF85I9QBYmbCIuVGWomQE8cA6lQ=
  skip_cleanup: true
  on:
    tags: true
    branch: master
